<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_create_greetercard_service.proto

namespace User\Greeter\Create;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户贺卡创建信息
 *
 * Generated from protobuf message <code>user.greeter.create.UserCreateGreeterCardInfo</code>
 */
class UserCreateGreeterCardInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *贺卡ID - 必填
     *
     * Generated from protobuf field <code>string greeterCardId = 2;</code>
     */
    private $greeterCardId = '';
    /**
     *贺卡信息 -选填
     *
     * Generated from protobuf field <code>string greeterCardInfo = 3;</code>
     */
    private $greeterCardInfo = '';
    /**
     *贺卡链接 - 选填
     *
     * Generated from protobuf field <code>string greeterCardLink = 4;</code>
     */
    private $greeterCardLink = '';
    /**
     *昵称-选填
     *
     * Generated from protobuf field <code>string nickName = 5;</code>
     */
    private $nickName = '';
    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 6;</code>
     */
    private $wxID = '';
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 7;</code>
     */
    private $token = '';
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 8;</code>
     */
    private $clientPlatform = '';
    /**
     *创建时间-必填
     *
     * Generated from protobuf field <code>int64 createTime = 9;</code>
     */
    private $createTime = 0;

    public function __construct() {
        \GPBMetadata\UserCreateGreetercardService::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *贺卡ID - 必填
     *
     * Generated from protobuf field <code>string greeterCardId = 2;</code>
     * @return string
     */
    public function getGreeterCardId()
    {
        return $this->greeterCardId;
    }

    /**
     *贺卡ID - 必填
     *
     * Generated from protobuf field <code>string greeterCardId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setGreeterCardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->greeterCardId = $var;

        return $this;
    }

    /**
     *贺卡信息 -选填
     *
     * Generated from protobuf field <code>string greeterCardInfo = 3;</code>
     * @return string
     */
    public function getGreeterCardInfo()
    {
        return $this->greeterCardInfo;
    }

    /**
     *贺卡信息 -选填
     *
     * Generated from protobuf field <code>string greeterCardInfo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setGreeterCardInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->greeterCardInfo = $var;

        return $this;
    }

    /**
     *贺卡链接 - 选填
     *
     * Generated from protobuf field <code>string greeterCardLink = 4;</code>
     * @return string
     */
    public function getGreeterCardLink()
    {
        return $this->greeterCardLink;
    }

    /**
     *贺卡链接 - 选填
     *
     * Generated from protobuf field <code>string greeterCardLink = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setGreeterCardLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->greeterCardLink = $var;

        return $this;
    }

    /**
     *昵称-选填
     *
     * Generated from protobuf field <code>string nickName = 5;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->nickName;
    }

    /**
     *昵称-选填
     *
     * Generated from protobuf field <code>string nickName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickName = $var;

        return $this;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 6;</code>
     * @return string
     */
    public function getWxID()
    {
        return $this->wxID;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWxID($var)
    {
        GPBUtil::checkString($var, True);
        $this->wxID = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 7;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 8;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

    /**
     *创建时间-必填
     *
     * Generated from protobuf field <code>int64 createTime = 9;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->createTime;
    }

    /**
     *创建时间-必填
     *
     * Generated from protobuf field <code>int64 createTime = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->createTime = $var;

        return $this;
    }

}

