<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_idcard_auth.proto

namespace User\Auth\Idcard;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户身份证验证信息
 *
 * Generated from protobuf message <code>user.auth.idcard.UserIDCardAuthInfo</code>
 */
class UserIDCardAuthInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *真实姓名-必填
     *
     * Generated from protobuf field <code>string realName = 2;</code>
     */
    private $realName = '';
    /**
     *身份证号码-必填
     *
     * Generated from protobuf field <code>string idCard = 3;</code>
     */
    private $idCard = '';
    /**
     *认证平台-必填
     *
     * Generated from protobuf field <code>string authPlatform = 4;</code>
     */
    private $authPlatform = '';
    /**
     *认证状态-必填
     *
     * Generated from protobuf field <code>.user.auth.idcard.UserIDCardAuthInfo.AuthStatus authStatus = 5;</code>
     */
    private $authStatus = 0;
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 6;</code>
     */
    private $token = '';
    /**
     *认证时间-必填
     *
     * Generated from protobuf field <code>int64 authTime = 7;</code>
     */
    private $authTime = 0;
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 8;</code>
     */
    private $clientPlatform = '';

    public function __construct() {
        \GPBMetadata\UserIdcardAuth::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *真实姓名-必填
     *
     * Generated from protobuf field <code>string realName = 2;</code>
     * @return string
     */
    public function getRealName()
    {
        return $this->realName;
    }

    /**
     *真实姓名-必填
     *
     * Generated from protobuf field <code>string realName = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setRealName($var)
    {
        GPBUtil::checkString($var, True);
        $this->realName = $var;

        return $this;
    }

    /**
     *身份证号码-必填
     *
     * Generated from protobuf field <code>string idCard = 3;</code>
     * @return string
     */
    public function getIdCard()
    {
        return $this->idCard;
    }

    /**
     *身份证号码-必填
     *
     * Generated from protobuf field <code>string idCard = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setIdCard($var)
    {
        GPBUtil::checkString($var, True);
        $this->idCard = $var;

        return $this;
    }

    /**
     *认证平台-必填
     *
     * Generated from protobuf field <code>string authPlatform = 4;</code>
     * @return string
     */
    public function getAuthPlatform()
    {
        return $this->authPlatform;
    }

    /**
     *认证平台-必填
     *
     * Generated from protobuf field <code>string authPlatform = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setAuthPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->authPlatform = $var;

        return $this;
    }

    /**
     *认证状态-必填
     *
     * Generated from protobuf field <code>.user.auth.idcard.UserIDCardAuthInfo.AuthStatus authStatus = 5;</code>
     * @return int
     */
    public function getAuthStatus()
    {
        return $this->authStatus;
    }

    /**
     *认证状态-必填
     *
     * Generated from protobuf field <code>.user.auth.idcard.UserIDCardAuthInfo.AuthStatus authStatus = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setAuthStatus($var)
    {
        GPBUtil::checkEnum($var, \User\Auth\Idcard\UserIDCardAuthInfo_AuthStatus::class);
        $this->authStatus = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *认证时间-必填
     *
     * Generated from protobuf field <code>int64 authTime = 7;</code>
     * @return int|string
     */
    public function getAuthTime()
    {
        return $this->authTime;
    }

    /**
     *认证时间-必填
     *
     * Generated from protobuf field <code>int64 authTime = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAuthTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->authTime = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 8;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

}

