<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_idcard_auth.proto

namespace User\Auth\Idcard;

/**
 * Protobuf enum <code>User\Auth\Idcard\UserIDCardAuthInfo\AuthStatus</code>
 */
class UserIDCardAuthInfo_AuthStatus
{
    /**
     * Generated from protobuf enum <code>SUC = 0;</code>
     */
    const SUC = 0;
    /**
     * Generated from protobuf enum <code>FAILED = 1;</code>
     */
    const FAILED = 1;
}

