<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_platform_em.proto

namespace Client\Platform;

/**
 *客户端平台enum，使用为enum.name
 *
 * Protobuf enum <code>Client\Platform\ClientPlatform</code>
 */
class ClientPlatform
{
    /**
     *WKWXAPP
     *
     * Generated from protobuf enum <code>WKWXAPP = 0;</code>
     */
    const WKWXAPP = 0;
    /**
     *WKIOS
     *
     * Generated from protobuf enum <code>WKIOS = 1;</code>
     */
    const WKIOS = 1;
    /**
     *WKANDROID
     *
     * Generated from protobuf enum <code>WKANDROID = 2;</code>
     */
    const WKANDROID = 2;
    /**
     * Generated from protobuf enum <code>A = 5;</code>
     */
    const A = 5;
    /**
     * Generated from protobuf enum <code>B = 6;</code>
     */
    const B = 6;
    /**
     * Generated from protobuf enum <code>C = 7;</code>
     */
    const C = 7;
    /**
     * Generated from protobuf enum <code>D = 8;</code>
     */
    const D = 8;
    /**
     * Generated from protobuf enum <code>E = 9;</code>
     */
    const E = 9;
    /**
     * WKWXAPP, WKIOS, WKANDROID
     *
     * Generated from protobuf enum <code>F = 10;</code>
     */
    const F = 10;
}

