<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_info_service.proto

namespace User;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户信息
 *
 * Generated from protobuf message <code>user.UserInfo</code>
 */
class UserInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *邮箱-选填
     *
     * Generated from protobuf field <code>string email = 2;</code>
     */
    private $email = '';
    /**
     *真实姓名-选填
     *
     * Generated from protobuf field <code>string realName = 3;</code>
     */
    private $realName = '';
    /**
     *身份证号码-选填
     *
     * Generated from protobuf field <code>string idCard = 4;</code>
     */
    private $idCard = '';
    /**
     *昵称-选填
     *
     * Generated from protobuf field <code>string nickName = 5;</code>
     */
    private $nickName = '';
    /**
     *用户渠道-必填(自然流量，推荐等来源)
     *
     * Generated from protobuf field <code>string userFromType = 6;</code>
     */
    private $userFromType = '';
    /**
     *头像-选填(base64 image byte)
     *
     * Generated from protobuf field <code>string avatar = 7;</code>
     */
    private $avatar = '';
    /**
     *用户操作类型 -  必填
     *
     * Generated from protobuf field <code>string userOperType = 8;</code>
     */
    private $userOperType = '';
    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 9;</code>
     */
    private $wxID = '';
    /**
     *QQID-选填
     *
     * Generated from protobuf field <code>string qqID = 10;</code>
     */
    private $qqID = '';
    /**
     *新浪微博ID-选填
     *
     * Generated from protobuf field <code>string sinaWeiBoID = 11;</code>
     */
    private $sinaWeiBoID = '';
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 12;</code>
     */
    private $token = '';
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 13;</code>
     */
    private $clientPlatform = '';
    /**
     *注册时间 - 必填
     *
     * Generated from protobuf field <code>int64 regTime = 14;</code>
     */
    private $regTime = 0;
    /**
     *IP - 选填
     *
     * Generated from protobuf field <code>string ip = 15;</code>
     */
    private $ip = '';

    public function __construct() {
        \GPBMetadata\UserInfoService::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *邮箱-选填
     *
     * Generated from protobuf field <code>string email = 2;</code>
     * @return string
     */
    public function getEmail()
    {
        return $this->email;
    }

    /**
     *邮箱-选填
     *
     * Generated from protobuf field <code>string email = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setEmail($var)
    {
        GPBUtil::checkString($var, True);
        $this->email = $var;

        return $this;
    }

    /**
     *真实姓名-选填
     *
     * Generated from protobuf field <code>string realName = 3;</code>
     * @return string
     */
    public function getRealName()
    {
        return $this->realName;
    }

    /**
     *真实姓名-选填
     *
     * Generated from protobuf field <code>string realName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setRealName($var)
    {
        GPBUtil::checkString($var, True);
        $this->realName = $var;

        return $this;
    }

    /**
     *身份证号码-选填
     *
     * Generated from protobuf field <code>string idCard = 4;</code>
     * @return string
     */
    public function getIdCard()
    {
        return $this->idCard;
    }

    /**
     *身份证号码-选填
     *
     * Generated from protobuf field <code>string idCard = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setIdCard($var)
    {
        GPBUtil::checkString($var, True);
        $this->idCard = $var;

        return $this;
    }

    /**
     *昵称-选填
     *
     * Generated from protobuf field <code>string nickName = 5;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->nickName;
    }

    /**
     *昵称-选填
     *
     * Generated from protobuf field <code>string nickName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickName = $var;

        return $this;
    }

    /**
     *用户渠道-必填(自然流量，推荐等来源)
     *
     * Generated from protobuf field <code>string userFromType = 6;</code>
     * @return string
     */
    public function getUserFromType()
    {
        return $this->userFromType;
    }

    /**
     *用户渠道-必填(自然流量，推荐等来源)
     *
     * Generated from protobuf field <code>string userFromType = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setUserFromType($var)
    {
        GPBUtil::checkString($var, True);
        $this->userFromType = $var;

        return $this;
    }

    /**
     *头像-选填(base64 image byte)
     *
     * Generated from protobuf field <code>string avatar = 7;</code>
     * @return string
     */
    public function getAvatar()
    {
        return $this->avatar;
    }

    /**
     *头像-选填(base64 image byte)
     *
     * Generated from protobuf field <code>string avatar = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setAvatar($var)
    {
        GPBUtil::checkString($var, True);
        $this->avatar = $var;

        return $this;
    }

    /**
     *用户操作类型 -  必填
     *
     * Generated from protobuf field <code>string userOperType = 8;</code>
     * @return string
     */
    public function getUserOperType()
    {
        return $this->userOperType;
    }

    /**
     *用户操作类型 -  必填
     *
     * Generated from protobuf field <code>string userOperType = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setUserOperType($var)
    {
        GPBUtil::checkString($var, True);
        $this->userOperType = $var;

        return $this;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 9;</code>
     * @return string
     */
    public function getWxID()
    {
        return $this->wxID;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setWxID($var)
    {
        GPBUtil::checkString($var, True);
        $this->wxID = $var;

        return $this;
    }

    /**
     *QQID-选填
     *
     * Generated from protobuf field <code>string qqID = 10;</code>
     * @return string
     */
    public function getQqID()
    {
        return $this->qqID;
    }

    /**
     *QQID-选填
     *
     * Generated from protobuf field <code>string qqID = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setQqID($var)
    {
        GPBUtil::checkString($var, True);
        $this->qqID = $var;

        return $this;
    }

    /**
     *新浪微博ID-选填
     *
     * Generated from protobuf field <code>string sinaWeiBoID = 11;</code>
     * @return string
     */
    public function getSinaWeiBoID()
    {
        return $this->sinaWeiBoID;
    }

    /**
     *新浪微博ID-选填
     *
     * Generated from protobuf field <code>string sinaWeiBoID = 11;</code>
     * @param string $var
     * @return $this
     */
    public function setSinaWeiBoID($var)
    {
        GPBUtil::checkString($var, True);
        $this->sinaWeiBoID = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 12;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 12;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 13;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 13;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

    /**
     *注册时间 - 必填
     *
     * Generated from protobuf field <code>int64 regTime = 14;</code>
     * @return int|string
     */
    public function getRegTime()
    {
        return $this->regTime;
    }

    /**
     *注册时间 - 必填
     *
     * Generated from protobuf field <code>int64 regTime = 14;</code>
     * @param int|string $var
     * @return $this
     */
    public function setRegTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->regTime = $var;

        return $this;
    }

    /**
     *IP - 选填
     *
     * Generated from protobuf field <code>string ip = 15;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     *IP - 选填
     *
     * Generated from protobuf field <code>string ip = 15;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

