<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_create_postcard_service.proto

namespace User\Postcard\Create;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户贺卡创建信息
 *
 * Generated from protobuf message <code>user.postcard.create.UserCreatePostCardInfo</code>
 */
class UserCreatePostCardInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *明信片ID - 必填
     *
     * Generated from protobuf field <code>string postCardId = 2;</code>
     */
    private $postCardId = '';
    /**
     *明信片信息 -选填
     *
     * Generated from protobuf field <code>string postCardInfo = 3;</code>
     */
    private $postCardInfo = '';
    /**
     *明信片链接 - 选填
     *
     * Generated from protobuf field <code>string postCardLink = 4;</code>
     */
    private $postCardLink = '';
    /**
     *昵称-选填
     *
     * Generated from protobuf field <code>string nickName = 5;</code>
     */
    private $nickName = '';
    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 6;</code>
     */
    private $wxID = '';
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 7;</code>
     */
    private $token = '';
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 8;</code>
     */
    private $clientPlatform = '';
    /**
     *创建时间-必填
     *
     * Generated from protobuf field <code>int64 createTime = 9;</code>
     */
    private $createTime = 0;

    public function __construct() {
        \GPBMetadata\UserCreatePostcardService::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *明信片ID - 必填
     *
     * Generated from protobuf field <code>string postCardId = 2;</code>
     * @return string
     */
    public function getPostCardId()
    {
        return $this->postCardId;
    }

    /**
     *明信片ID - 必填
     *
     * Generated from protobuf field <code>string postCardId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setPostCardId($var)
    {
        GPBUtil::checkString($var, True);
        $this->postCardId = $var;

        return $this;
    }

    /**
     *明信片信息 -选填
     *
     * Generated from protobuf field <code>string postCardInfo = 3;</code>
     * @return string
     */
    public function getPostCardInfo()
    {
        return $this->postCardInfo;
    }

    /**
     *明信片信息 -选填
     *
     * Generated from protobuf field <code>string postCardInfo = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPostCardInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->postCardInfo = $var;

        return $this;
    }

    /**
     *明信片链接 - 选填
     *
     * Generated from protobuf field <code>string postCardLink = 4;</code>
     * @return string
     */
    public function getPostCardLink()
    {
        return $this->postCardLink;
    }

    /**
     *明信片链接 - 选填
     *
     * Generated from protobuf field <code>string postCardLink = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setPostCardLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->postCardLink = $var;

        return $this;
    }

    /**
     *昵称-选填
     *
     * Generated from protobuf field <code>string nickName = 5;</code>
     * @return string
     */
    public function getNickName()
    {
        return $this->nickName;
    }

    /**
     *昵称-选填
     *
     * Generated from protobuf field <code>string nickName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setNickName($var)
    {
        GPBUtil::checkString($var, True);
        $this->nickName = $var;

        return $this;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 6;</code>
     * @return string
     */
    public function getWxID()
    {
        return $this->wxID;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setWxID($var)
    {
        GPBUtil::checkString($var, True);
        $this->wxID = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 7;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 8;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

    /**
     *创建时间-必填
     *
     * Generated from protobuf field <code>int64 createTime = 9;</code>
     * @return int|string
     */
    public function getCreateTime()
    {
        return $this->createTime;
    }

    /**
     *创建时间-必填
     *
     * Generated from protobuf field <code>int64 createTime = 9;</code>
     * @param int|string $var
     * @return $this
     */
    public function setCreateTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->createTime = $var;

        return $this;
    }

}

