<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: client_platform_em.proto

namespace GPBMetadata;

class ClientPlatformEm
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ade010a18636c69656e745f706c6174666f726d5f656d2e70726f746f12" .
            "0f636c69656e742e706c6174666f726d2a610a0e436c69656e74506c6174" .
            "666f726d120b0a07574b5758415050100012090a05574b494f531001120d" .
            "0a09574b414e44524f4944100212050a0141100512050a0142100612050a" .
            "0143100712050a0144100812050a0145100912050a0146100a42460a2563" .
            "6f6d2e7469616e7a686978696e672e6f6d732e677270632e70726f746f2e" .
            "636c69656e74421b436c69656e74506c6174666f726d496e666f456e756d" .
            "50726f746f5001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

