<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_entity.proto

namespace GPBMetadata;

class ResponseEntity
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a89010a15726573706f6e73655f656e746974792e70726f746f222f0a0e" .
            "526573706f6e7365456e74697479120c0a04636f6465180120012805120f" .
            "0a076d65737361676518022001280942370a1e636f6d2e7469616e7a6869" .
            "78696e672e6f6d732e677270632e70726f746f4213526573706f6e736545" .
            "6e7469747950726f746f5001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

