<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_login_service.proto

namespace GPBMetadata;

class UserLoginService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ResponseEntity::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a8e030a18757365725f6c6f67696e5f736572766963652e70726f746f12" .
            "0a757365722e6c6f67696e2296010a0d557365724c6f67696e496e666f12" .
            "0e0a066d6f62696c6518012001280912110a096c6f67696e54696d651802" .
            "2001280312160a0e636c69656e74506c6174666f726d180320012809120d" .
            "0a05746f6b656e180420012809120c0a0477784944180520012809120c0a" .
            "047171494418062001280912130a0b73696e61576569426f494418072001" .
            "2809120a0a02697018082001280922310a06526573756c7412270a0e7265" .
            "73706f6e7365456e7469747918012001280b320f2e526573706f6e736545" .
            "6e74697479324c0a10557365724c6f67696e5365727669636512380a056c" .
            "6f67696e12192e757365722e6c6f67696e2e557365724c6f67696e496e66" .
            "6f1a122e757365722e6c6f67696e2e526573756c74220042440a29636f6d" .
            "2e7469616e7a686978696e672e6f6d732e677270632e70726f746f2e7573" .
            "65722e6c6f67696e4215557365724c6f67696e5365727669636550726f74" .
            "6f5001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

