<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_logout_service.proto

namespace GPBMetadata;

class UserLogoutService
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ResponseEntity::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0a99030a19757365725f6c6f676f75745f736572766963652e70726f746f" .
            "120b757365722e6c6f676f75742298010a0e557365724c6f676f7574496e" .
            "666f120e0a066d6f62696c6518012001280912120a0a6c6f676f75745469" .
            "6d6518022001280312160a0e636c69656e74506c6174666f726d18032001" .
            "2809120d0a05746f6b656e180420012809120c0a04777849441805200128" .
            "09120c0a047171494418062001280912130a0b73696e61576569426f4944" .
            "180720012809120a0a02697018082001280922310a06526573756c741227" .
            "0a0e726573706f6e7365456e7469747918012001280b320f2e526573706f" .
            "6e7365456e7469747932510a11557365724c6f676f757453657276696365" .
            "123c0a066c6f676f7574121b2e757365722e6c6f676f75742e557365724c" .
            "6f676f7574496e666f1a132e757365722e6c6f676f75742e526573756c74" .
            "220042460a2a636f6d2e7469616e7a686978696e672e6f6d732e67727063" .
            "2e70726f746f2e757365722e6c6f676f75744216557365724c6f676f7574" .
            "5365727669636550726f746f5001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

