<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wx_application_user_login_service.proto.discardfile

namespace GPBMetadata;

class WxApplicationUserLoginServiceProto
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ResponseEntity::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae1030a3377785f6170706c69636174696f6e5f757365725f6c6f67696e" .
            "5f736572766963652e70726f746f2e6469736361726466696c65120d7573" .
            "65722e6c6f67696e2e77782298010a1b5758416170706c69636174696f6e" .
            "557365724c6f67696e496e666f120e0a066d6f62696c6518012001280912" .
            "110a096c6f67696e54696d6518022001280312160a0e636c69656e74506c" .
            "6174666f726d180320012809120d0a05746f6b656e180420012809120c0a" .
            "0477784944180520012809120c0a047171494418062001280912130a0b73" .
            "696e61576569426f494418072001280922310a06526573756c7412270a0e" .
            "726573706f6e7365456e7469747918012001280b320f2e526573706f6e73" .
            "65456e74697479326e0a1e5758416170706c69636174696f6e557365724c" .
            "6f67696e53657276696365124c0a056c6f67696e122a2e757365722e6c6f" .
            "67696e2e77782e5758416170706c69636174696f6e557365724c6f67696e" .
            "496e666f1a152e757365722e6c6f67696e2e77782e526573756c74220042" .
            "550a2c636f6d2e7469616e7a686978696e672e6f6d732e677270632e7072" .
            "6f746f2e757365722e6c6f67696e2e777842235758416170706c69636174" .
            "696f6e557365724c6f67696e5365727669636550726f746f500162067072" .
            "6f746f33"
        ));

        static::$is_initialized = true;
    }
}

