<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wx_application_user_logout_service.proto.discardfile

namespace GPBMetadata;

class WxApplicationUserLogoutServiceProto
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        \GPBMetadata\ResponseEntity::initOnce();
        $pool->internalAddGeneratedFile(hex2bin(
            "0ae8030a3477785f6170706c69636174696f6e5f757365725f6c6f676f75" .
            "745f736572766963652e70726f746f2e6469736361726466696c65120e75" .
            "7365722e6c6f676f75742e77782299010a1b57584170706c69636174696f" .
            "6e557365724c6f676f7574496e666f120e0a066d6f62696c651801200128" .
            "0912120a0a6c6f676f757454696d6518022001280312160a0e636c69656e" .
            "74506c6174666f726d180320012809120d0a05746f6b656e180420012809" .
            "120c0a0477784944180520012809120c0a04717149441806200128091213" .
            "0a0b73696e61576569426f494418072001280922310a06526573756c7412" .
            "270a0e726573706f6e7365456e7469747918012001280b320f2e52657370" .
            "6f6e7365456e7469747932710a1e57584170706c69636174696f6e557365" .
            "724c6f676f757453657276696365124f0a066c6f676f7574122b2e757365" .
            "722e6c6f676f75742e77782e57584170706c69636174696f6e557365724c" .
            "6f676f7574496e666f1a162e757365722e6c6f676f75742e77782e526573" .
            "756c74220042560a2d636f6d2e7469616e7a686978696e672e6f6d732e67" .
            "7270632e70726f746f2e757365722e6c6f676f75742e7778422357584170" .
            "706c69636174696f6e557365724c6f676f75745365727669636550726f74" .
            "6f5001620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

