<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: application_operation.proto

namespace App\Operation;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *app 启动信息
 *
 * Generated from protobuf message <code>app.operation.ApplicationStartInfo</code>
 */
class ApplicationStartInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-选填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 2;</code>
     */
    private $wxID = '';
    /**
     *启动时间-必填
     *
     * Generated from protobuf field <code>int64 startTime = 3;</code>
     */
    private $startTime = 0;
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 4;</code>
     */
    private $token = '';
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 5;</code>
     */
    private $clientPlatform = '';
    /**
     *IP - 必填
     *
     * Generated from protobuf field <code>string ip = 6;</code>
     */
    private $ip = '';

    public function __construct() {
        \GPBMetadata\ApplicationOperation::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-选填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-选填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 2;</code>
     * @return string
     */
    public function getWxID()
    {
        return $this->wxID;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWxID($var)
    {
        GPBUtil::checkString($var, True);
        $this->wxID = $var;

        return $this;
    }

    /**
     *启动时间-必填
     *
     * Generated from protobuf field <code>int64 startTime = 3;</code>
     * @return int|string
     */
    public function getStartTime()
    {
        return $this->startTime;
    }

    /**
     *启动时间-必填
     *
     * Generated from protobuf field <code>int64 startTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setStartTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->startTime = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 4;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 5;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

    /**
     *IP - 必填
     *
     * Generated from protobuf field <code>string ip = 6;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     *IP - 必填
     *
     * Generated from protobuf field <code>string ip = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

