<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_satellite_operation_address.proto

namespace Statellite\Oper\Address;

/**
 * Protobuf enum <code>Statellite\Oper\Address\UserSatelliteOperationAddressInfo\OperationType</code>
 */
class UserSatelliteOperationAddressInfo_OperationType
{
    /**
     * Generated from protobuf enum <code>ONE = 0;</code>
     */
    const ONE = 0;
    /**
     * Generated from protobuf enum <code>TWO = 1;</code>
     */
    const TWO = 1;
    /**
     * Generated from protobuf enum <code>THREE = 2;</code>
     */
    const THREE = 2;
}

