<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_appointment.proto

namespace User\Appointment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户预约信息
 *
 * Generated from protobuf message <code>user.appointment.UserAppointmentInfo</code>
 */
class UserAppointmentInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *预约内容-必填
     *
     * Generated from protobuf field <code>string appointmentContent = 2;</code>
     */
    private $appointmentContent = '';
    /**
     *预约时间-必填
     *
     * Generated from protobuf field <code>int64 appointmentTime = 3;</code>
     */
    private $appointmentTime = 0;
    /**
     *预约未来时间 - 必填
     *
     * Generated from protobuf field <code>int64 appointmentFutureTime = 4;</code>
     */
    private $appointmentFutureTime = 0;
    /**
     *预约类型 - 必填(操控卫星/语音墙)
     *
     * Generated from protobuf field <code>string appointmentType = 5;</code>
     */
    private $appointmentType = '';
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 6;</code>
     */
    private $token = '';
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 7;</code>
     */
    private $clientPlatform = '';

    public function __construct() {
        \GPBMetadata\UserAppointment::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *预约内容-必填
     *
     * Generated from protobuf field <code>string appointmentContent = 2;</code>
     * @return string
     */
    public function getAppointmentContent()
    {
        return $this->appointmentContent;
    }

    /**
     *预约内容-必填
     *
     * Generated from protobuf field <code>string appointmentContent = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAppointmentContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->appointmentContent = $var;

        return $this;
    }

    /**
     *预约时间-必填
     *
     * Generated from protobuf field <code>int64 appointmentTime = 3;</code>
     * @return int|string
     */
    public function getAppointmentTime()
    {
        return $this->appointmentTime;
    }

    /**
     *预约时间-必填
     *
     * Generated from protobuf field <code>int64 appointmentTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAppointmentTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->appointmentTime = $var;

        return $this;
    }

    /**
     *预约未来时间 - 必填
     *
     * Generated from protobuf field <code>int64 appointmentFutureTime = 4;</code>
     * @return int|string
     */
    public function getAppointmentFutureTime()
    {
        return $this->appointmentFutureTime;
    }

    /**
     *预约未来时间 - 必填
     *
     * Generated from protobuf field <code>int64 appointmentFutureTime = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAppointmentFutureTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->appointmentFutureTime = $var;

        return $this;
    }

    /**
     *预约类型 - 必填(操控卫星/语音墙)
     *
     * Generated from protobuf field <code>string appointmentType = 5;</code>
     * @return string
     */
    public function getAppointmentType()
    {
        return $this->appointmentType;
    }

    /**
     *预约类型 - 必填(操控卫星/语音墙)
     *
     * Generated from protobuf field <code>string appointmentType = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAppointmentType($var)
    {
        GPBUtil::checkString($var, True);
        $this->appointmentType = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 7;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

}

