<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_star_point_increment.proto

namespace Start\Point\Increment;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户星点增长信息
 *
 * Generated from protobuf message <code>start.point.increment.UserStarPointIncrementInfo</code>
 */
class UserStarPointIncrementInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *任务ID-选填
     *
     * Generated from protobuf field <code>string taskId = 2;</code>
     */
    private $taskId = '';
    /**
     *任务名称-选填
     *
     * Generated from protobuf field <code>string taskName = 3;</code>
     */
    private $taskName = '';
    /**
     *任务信息-选填
     *
     * Generated from protobuf field <code>string taskInfo = 4;</code>
     */
    private $taskInfo = '';
    /**
     *增长时间-必填
     *
     * Generated from protobuf field <code>int64 incrementTime = 5;</code>
     */
    private $incrementTime = 0;
    /**
     *增长数量-必填
     *
     * Generated from protobuf field <code>string incrementCount = 6;</code>
     */
    private $incrementCount = '';
    /**
     *增长原因-必填
     *
     * Generated from protobuf field <code>string incrementCause = 7;</code>
     */
    private $incrementCause = '';
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 8;</code>
     */
    private $token = '';
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 9;</code>
     */
    private $clientPlatform = '';

    public function __construct() {
        \GPBMetadata\UserStarPointIncrement::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *任务ID-选填
     *
     * Generated from protobuf field <code>string taskId = 2;</code>
     * @return string
     */
    public function getTaskId()
    {
        return $this->taskId;
    }

    /**
     *任务ID-选填
     *
     * Generated from protobuf field <code>string taskId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskId($var)
    {
        GPBUtil::checkString($var, True);
        $this->taskId = $var;

        return $this;
    }

    /**
     *任务名称-选填
     *
     * Generated from protobuf field <code>string taskName = 3;</code>
     * @return string
     */
    public function getTaskName()
    {
        return $this->taskName;
    }

    /**
     *任务名称-选填
     *
     * Generated from protobuf field <code>string taskName = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskName($var)
    {
        GPBUtil::checkString($var, True);
        $this->taskName = $var;

        return $this;
    }

    /**
     *任务信息-选填
     *
     * Generated from protobuf field <code>string taskInfo = 4;</code>
     * @return string
     */
    public function getTaskInfo()
    {
        return $this->taskInfo;
    }

    /**
     *任务信息-选填
     *
     * Generated from protobuf field <code>string taskInfo = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setTaskInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->taskInfo = $var;

        return $this;
    }

    /**
     *增长时间-必填
     *
     * Generated from protobuf field <code>int64 incrementTime = 5;</code>
     * @return int|string
     */
    public function getIncrementTime()
    {
        return $this->incrementTime;
    }

    /**
     *增长时间-必填
     *
     * Generated from protobuf field <code>int64 incrementTime = 5;</code>
     * @param int|string $var
     * @return $this
     */
    public function setIncrementTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->incrementTime = $var;

        return $this;
    }

    /**
     *增长数量-必填
     *
     * Generated from protobuf field <code>string incrementCount = 6;</code>
     * @return string
     */
    public function getIncrementCount()
    {
        return $this->incrementCount;
    }

    /**
     *增长数量-必填
     *
     * Generated from protobuf field <code>string incrementCount = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setIncrementCount($var)
    {
        GPBUtil::checkString($var, True);
        $this->incrementCount = $var;

        return $this;
    }

    /**
     *增长原因-必填
     *
     * Generated from protobuf field <code>string incrementCause = 7;</code>
     * @return string
     */
    public function getIncrementCause()
    {
        return $this->incrementCause;
    }

    /**
     *增长原因-必填
     *
     * Generated from protobuf field <code>string incrementCause = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setIncrementCause($var)
    {
        GPBUtil::checkString($var, True);
        $this->incrementCause = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 8;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 9;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

}

