<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_click_advertisement.proto

namespace User\Advert;

/**
 * Protobuf enum <code>User\Advert\UserClickAdvertInfo\AdvertType</code>
 */
class UserClickAdvertInfo_AdvertType
{
    /**
     * Generated from protobuf enum <code>A = 0;</code>
     */
    const A = 0;
    /**
     * Generated from protobuf enum <code>B = 1;</code>
     */
    const B = 1;
    /**
     * Generated from protobuf enum <code>C = 3;</code>
     */
    const C = 3;
    /**
     * Generated from protobuf enum <code>D = 4;</code>
     */
    const D = 4;
    /**
     * Generated from protobuf enum <code>E = 5;</code>
     */
    const E = 5;
    /**
     * Generated from protobuf enum <code>F = 6;</code>
     */
    const F = 6;
    /**
     * Generated from protobuf enum <code>G = 7;</code>
     */
    const G = 7;
}

