<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_click_advertisement.proto

namespace User\Advert;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户点击广告信息
 *
 * Generated from protobuf message <code>user.advert.UserClickAdvertInfo</code>
 */
class UserClickAdvertInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *广告ID-必填
     *
     * Generated from protobuf field <code>string advertId = 2;</code>
     */
    private $advertId = '';
    /**
     *广告链接-选填
     *
     * Generated from protobuf field <code>string advertLink = 3;</code>
     */
    private $advertLink = '';
    /**
     *广告类型-必填
     *
     * Generated from protobuf field <code>.user.advert.UserClickAdvertInfo.AdvertType advertType = 4;</code>
     */
    private $advertType = 0;
    /**
     *广告名字-必填
     *
     * Generated from protobuf field <code>string advertName = 5;</code>
     */
    private $advertName = '';
    /**
     *广告信息-必填
     *
     * Generated from protobuf field <code>string advertInfo = 6;</code>
     */
    private $advertInfo = '';
    /**
     *点击时间-必填
     *
     * Generated from protobuf field <code>int64 clickTime = 7;</code>
     */
    private $clickTime = 0;
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 8;</code>
     */
    private $token = '';
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 9;</code>
     */
    private $clientPlatform = '';
    /**
     *IP - 必填
     *
     * Generated from protobuf field <code>string ip = 10;</code>
     */
    private $ip = '';

    public function __construct() {
        \GPBMetadata\UserClickAdvertisement::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *广告ID-必填
     *
     * Generated from protobuf field <code>string advertId = 2;</code>
     * @return string
     */
    public function getAdvertId()
    {
        return $this->advertId;
    }

    /**
     *广告ID-必填
     *
     * Generated from protobuf field <code>string advertId = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setAdvertId($var)
    {
        GPBUtil::checkString($var, True);
        $this->advertId = $var;

        return $this;
    }

    /**
     *广告链接-选填
     *
     * Generated from protobuf field <code>string advertLink = 3;</code>
     * @return string
     */
    public function getAdvertLink()
    {
        return $this->advertLink;
    }

    /**
     *广告链接-选填
     *
     * Generated from protobuf field <code>string advertLink = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setAdvertLink($var)
    {
        GPBUtil::checkString($var, True);
        $this->advertLink = $var;

        return $this;
    }

    /**
     *广告类型-必填
     *
     * Generated from protobuf field <code>.user.advert.UserClickAdvertInfo.AdvertType advertType = 4;</code>
     * @return int
     */
    public function getAdvertType()
    {
        return $this->advertType;
    }

    /**
     *广告类型-必填
     *
     * Generated from protobuf field <code>.user.advert.UserClickAdvertInfo.AdvertType advertType = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setAdvertType($var)
    {
        GPBUtil::checkEnum($var, \User\Advert\UserClickAdvertInfo_AdvertType::class);
        $this->advertType = $var;

        return $this;
    }

    /**
     *广告名字-必填
     *
     * Generated from protobuf field <code>string advertName = 5;</code>
     * @return string
     */
    public function getAdvertName()
    {
        return $this->advertName;
    }

    /**
     *广告名字-必填
     *
     * Generated from protobuf field <code>string advertName = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setAdvertName($var)
    {
        GPBUtil::checkString($var, True);
        $this->advertName = $var;

        return $this;
    }

    /**
     *广告信息-必填
     *
     * Generated from protobuf field <code>string advertInfo = 6;</code>
     * @return string
     */
    public function getAdvertInfo()
    {
        return $this->advertInfo;
    }

    /**
     *广告信息-必填
     *
     * Generated from protobuf field <code>string advertInfo = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setAdvertInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->advertInfo = $var;

        return $this;
    }

    /**
     *点击时间-必填
     *
     * Generated from protobuf field <code>int64 clickTime = 7;</code>
     * @return int|string
     */
    public function getClickTime()
    {
        return $this->clickTime;
    }

    /**
     *点击时间-必填
     *
     * Generated from protobuf field <code>int64 clickTime = 7;</code>
     * @param int|string $var
     * @return $this
     */
    public function setClickTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->clickTime = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 8;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 8;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 9;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

    /**
     *IP - 必填
     *
     * Generated from protobuf field <code>string ip = 10;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     *IP - 必填
     *
     * Generated from protobuf field <code>string ip = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

