<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_star_point_consume.proto

namespace Start\Point\Consume;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户星点消费信息
 *
 * Generated from protobuf message <code>start.point.consume.UserStarPointConsumeInfo</code>
 */
class UserStarPointConsumeInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *消费时间-必填
     *
     * Generated from protobuf field <code>int64 consumeTime = 2;</code>
     */
    private $consumeTime = 0;
    /**
     *消费数量-必填(0.001/0.01/1)
     *
     * Generated from protobuf field <code>string consumeCount = 3;</code>
     */
    private $consumeCount = '';
    /**
     *消费原因-必填
     *
     * Generated from protobuf field <code>string consumeCause = 4;</code>
     */
    private $consumeCause = '';
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 5;</code>
     */
    private $token = '';
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 6;</code>
     */
    private $clientPlatform = '';

    public function __construct() {
        \GPBMetadata\UserStarPointConsume::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *消费时间-必填
     *
     * Generated from protobuf field <code>int64 consumeTime = 2;</code>
     * @return int|string
     */
    public function getConsumeTime()
    {
        return $this->consumeTime;
    }

    /**
     *消费时间-必填
     *
     * Generated from protobuf field <code>int64 consumeTime = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setConsumeTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->consumeTime = $var;

        return $this;
    }

    /**
     *消费数量-必填(0.001/0.01/1)
     *
     * Generated from protobuf field <code>string consumeCount = 3;</code>
     * @return string
     */
    public function getConsumeCount()
    {
        return $this->consumeCount;
    }

    /**
     *消费数量-必填(0.001/0.01/1)
     *
     * Generated from protobuf field <code>string consumeCount = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setConsumeCount($var)
    {
        GPBUtil::checkString($var, True);
        $this->consumeCount = $var;

        return $this;
    }

    /**
     *消费原因-必填
     *
     * Generated from protobuf field <code>string consumeCause = 4;</code>
     * @return string
     */
    public function getConsumeCause()
    {
        return $this->consumeCause;
    }

    /**
     *消费原因-必填
     *
     * Generated from protobuf field <code>string consumeCause = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setConsumeCause($var)
    {
        GPBUtil::checkString($var, True);
        $this->consumeCause = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 5;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 6;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

}

