<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: response_entity.proto

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *返回信息
 *
 * Generated from protobuf message <code>ResponseEntity</code>
 */
class ResponseEntity extends \Google\Protobuf\Internal\Message
{
    /**
     *请求状态 200=请求处理成功，500=请求处理失败，300=业务逻辑失败（message）
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     */
    private $code = 0;
    /**
     *信息
     *
     * Generated from protobuf field <code>string message = 2;</code>
     */
    private $message = '';

    public function __construct() {
        \GPBMetadata\ResponseEntity::initOnce();
        parent::__construct();
    }

    /**
     *请求状态 200=请求处理成功，500=请求处理失败，300=业务逻辑失败（message）
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @return int
     */
    public function getCode()
    {
        return $this->code;
    }

    /**
     *请求状态 200=请求处理成功，500=请求处理失败，300=业务逻辑失败（message）
     *
     * Generated from protobuf field <code>int32 code = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setCode($var)
    {
        GPBUtil::checkInt32($var);
        $this->code = $var;

        return $this;
    }

    /**
     *信息
     *
     * Generated from protobuf field <code>string message = 2;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     *信息
     *
     * Generated from protobuf field <code>string message = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

}

