<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_satellite_operation.proto

namespace Statellite\Oper;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *用户卫星操控信息
 *
 * Generated from protobuf message <code>statellite.oper.UserSatelliteOperationInfo</code>
 */
class UserSatelliteOperationInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *操作内容-必填
     *
     * Generated from protobuf field <code>string operationContent = 2;</code>
     */
    private $operationContent = '';
    /**
     *操作时间-必填
     *
     * Generated from protobuf field <code>int64 operationTime = 3;</code>
     */
    private $operationTime = 0;
    /**
     *操作类型 - 必填
     *
     * Generated from protobuf field <code>.statellite.oper.UserSatelliteOperationInfo.OperationType operationType = 5;</code>
     */
    private $operationType = 0;
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 6;</code>
     */
    private $token = '';
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 7;</code>
     */
    private $clientPlatform = '';

    public function __construct() {
        \GPBMetadata\UserSatelliteOperation::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-必填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *操作内容-必填
     *
     * Generated from protobuf field <code>string operationContent = 2;</code>
     * @return string
     */
    public function getOperationContent()
    {
        return $this->operationContent;
    }

    /**
     *操作内容-必填
     *
     * Generated from protobuf field <code>string operationContent = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setOperationContent($var)
    {
        GPBUtil::checkString($var, True);
        $this->operationContent = $var;

        return $this;
    }

    /**
     *操作时间-必填
     *
     * Generated from protobuf field <code>int64 operationTime = 3;</code>
     * @return int|string
     */
    public function getOperationTime()
    {
        return $this->operationTime;
    }

    /**
     *操作时间-必填
     *
     * Generated from protobuf field <code>int64 operationTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setOperationTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->operationTime = $var;

        return $this;
    }

    /**
     *操作类型 - 必填
     *
     * Generated from protobuf field <code>.statellite.oper.UserSatelliteOperationInfo.OperationType operationType = 5;</code>
     * @return int
     */
    public function getOperationType()
    {
        return $this->operationType;
    }

    /**
     *操作类型 - 必填
     *
     * Generated from protobuf field <code>.statellite.oper.UserSatelliteOperationInfo.OperationType operationType = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setOperationType($var)
    {
        GPBUtil::checkEnum($var, \Statellite\Oper\UserSatelliteOperationInfo_OperationType::class);
        $this->operationType = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 7;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

}

