<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pages_operation.proto

namespace Pages\Oper;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 *页面操作信息
 *
 * Generated from protobuf message <code>pages.oper.PagesOperationInfo</code>
 */
class PagesOperationInfo extends \Google\Protobuf\Internal\Message
{
    /**
     *手机号码-选填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     */
    private $mobile = '';
    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 2;</code>
     */
    private $wxID = '';
    /**
     *访问时间-必填
     *
     * Generated from protobuf field <code>int64 accessTime = 3;</code>
     */
    private $accessTime = 0;
    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 4;</code>
     */
    private $token = '';
    /**
     *页面地址-必填
     *
     * Generated from protobuf field <code>string pagesURL = 5;</code>
     */
    private $pagesURL = '';
    /**
     *页面信息-选填
     *
     * Generated from protobuf field <code>string pagesInfo = 6;</code>
     */
    private $pagesInfo = '';
    /**
     *页面名字-必填
     *
     * Generated from protobuf field <code>string pagesName = 7;</code>
     */
    private $pagesName = '';
    /**
     *登录状态 - LoginStatus enum name value, 必填
     *
     * Generated from protobuf field <code>.pages.oper.PagesOperationInfo.LoginStatus loginStatus = 8;</code>
     */
    private $loginStatus = 0;
    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 9;</code>
     */
    private $clientPlatform = '';
    /**
     *IP - 必填
     *
     * Generated from protobuf field <code>string ip = 10;</code>
     */
    private $ip = '';

    public function __construct() {
        \GPBMetadata\PagesOperation::initOnce();
        parent::__construct();
    }

    /**
     *手机号码-选填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @return string
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     *手机号码-选填
     *
     * Generated from protobuf field <code>string mobile = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMobile($var)
    {
        GPBUtil::checkString($var, True);
        $this->mobile = $var;

        return $this;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 2;</code>
     * @return string
     */
    public function getWxID()
    {
        return $this->wxID;
    }

    /**
     *微信ID-选填
     *
     * Generated from protobuf field <code>string wxID = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setWxID($var)
    {
        GPBUtil::checkString($var, True);
        $this->wxID = $var;

        return $this;
    }

    /**
     *访问时间-必填
     *
     * Generated from protobuf field <code>int64 accessTime = 3;</code>
     * @return int|string
     */
    public function getAccessTime()
    {
        return $this->accessTime;
    }

    /**
     *访问时间-必填
     *
     * Generated from protobuf field <code>int64 accessTime = 3;</code>
     * @param int|string $var
     * @return $this
     */
    public function setAccessTime($var)
    {
        GPBUtil::checkInt64($var);
        $this->accessTime = $var;

        return $this;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 4;</code>
     * @return string
     */
    public function getToken()
    {
        return $this->token;
    }

    /**
     *安全校验码-必填
     *
     * Generated from protobuf field <code>string token = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setToken($var)
    {
        GPBUtil::checkString($var, True);
        $this->token = $var;

        return $this;
    }

    /**
     *页面地址-必填
     *
     * Generated from protobuf field <code>string pagesURL = 5;</code>
     * @return string
     */
    public function getPagesURL()
    {
        return $this->pagesURL;
    }

    /**
     *页面地址-必填
     *
     * Generated from protobuf field <code>string pagesURL = 5;</code>
     * @param string $var
     * @return $this
     */
    public function setPagesURL($var)
    {
        GPBUtil::checkString($var, True);
        $this->pagesURL = $var;

        return $this;
    }

    /**
     *页面信息-选填
     *
     * Generated from protobuf field <code>string pagesInfo = 6;</code>
     * @return string
     */
    public function getPagesInfo()
    {
        return $this->pagesInfo;
    }

    /**
     *页面信息-选填
     *
     * Generated from protobuf field <code>string pagesInfo = 6;</code>
     * @param string $var
     * @return $this
     */
    public function setPagesInfo($var)
    {
        GPBUtil::checkString($var, True);
        $this->pagesInfo = $var;

        return $this;
    }

    /**
     *页面名字-必填
     *
     * Generated from protobuf field <code>string pagesName = 7;</code>
     * @return string
     */
    public function getPagesName()
    {
        return $this->pagesName;
    }

    /**
     *页面名字-必填
     *
     * Generated from protobuf field <code>string pagesName = 7;</code>
     * @param string $var
     * @return $this
     */
    public function setPagesName($var)
    {
        GPBUtil::checkString($var, True);
        $this->pagesName = $var;

        return $this;
    }

    /**
     *登录状态 - LoginStatus enum name value, 必填
     *
     * Generated from protobuf field <code>.pages.oper.PagesOperationInfo.LoginStatus loginStatus = 8;</code>
     * @return int
     */
    public function getLoginStatus()
    {
        return $this->loginStatus;
    }

    /**
     *登录状态 - LoginStatus enum name value, 必填
     *
     * Generated from protobuf field <code>.pages.oper.PagesOperationInfo.LoginStatus loginStatus = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setLoginStatus($var)
    {
        GPBUtil::checkEnum($var, \Pages\Oper\PagesOperationInfo_LoginStatus::class);
        $this->loginStatus = $var;

        return $this;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 9;</code>
     * @return string
     */
    public function getClientPlatform()
    {
        return $this->clientPlatform;
    }

    /**
     *客户端平台 - ClientPlatform( WKWXAPP 挖矿WX小程序, WKIOS 挖矿APP IOS, WKANDROID 挖矿 APP ANDROID), 必填
     *
     * Generated from protobuf field <code>string clientPlatform = 9;</code>
     * @param string $var
     * @return $this
     */
    public function setClientPlatform($var)
    {
        GPBUtil::checkString($var, True);
        $this->clientPlatform = $var;

        return $this;
    }

    /**
     *IP - 必填
     *
     * Generated from protobuf field <code>string ip = 10;</code>
     * @return string
     */
    public function getIp()
    {
        return $this->ip;
    }

    /**
     *IP - 必填
     *
     * Generated from protobuf field <code>string ip = 10;</code>
     * @param string $var
     * @return $this
     */
    public function setIp($var)
    {
        GPBUtil::checkString($var, True);
        $this->ip = $var;

        return $this;
    }

}

