<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pages_operation.proto

namespace Pages\Oper;

/**
 *登录状态enum
 *
 * Protobuf enum <code>Pages\Oper\PagesOperationInfo\LoginStatus</code>
 */
class PagesOperationInfo_LoginStatus
{
    /**
     * Generated from protobuf enum <code>NOTLOGIN = 0;</code>
     */
    const NOTLOGIN = 0;
    /**
     * Generated from protobuf enum <code>LOGIN = 1;</code>
     */
    const LOGIN = 1;
}

